#!/usr/bin/env python3

import rclpy
from rclpy.node import Node

import numpy as np
import os
import casadi

from uuv_auv_control_allocator.msg import AUVCommand
from uuv_auv_actuator_interface import ActuatorManager


class AUVControlAllocator(Node, ActuatorManager):

    def __init__(self):

        Node.__init__(
            self,
            'auv_control_allocator'
        )

        ActuatorManager.__init__(self)

        self.declare_parameter(
            'output_dir',
            ''
        )

        self.declare_parameter(
            'update_rate',
            10.0
        )

        self.declare_parameter(
            'timeout',
            -1.0
        )

        self.output_dir = self.get_parameter(
            'output_dir'
        ).value

        self.update_rate = self.get_parameter(
            'update_rate'
        ).value

        self.timeout = self.get_parameter(
            'timeout'
        ).value

        if self.output_dir != '':

            if not os.path.isdir(
                self.output_dir
            ):

                raise RuntimeError(
                    'Invalid output directory'
                )

            self.get_logger().info(
                f'output_dir={self.output_dir}'
            )

        if self.update_rate <= 0:

            raise RuntimeError(
                'Update rate must be positive'
            )

        self.u = casadi.SX.sym(
            'u'
        )

        self.thrust = casadi.SX.sym(
            'thrust'
        )

        self.delta = None

        self.output_tau = casadi.SX.sym(
            'tau',
            6,
            1
        )

        self.input_surge_speed = 0.0

        self.input_tau = np.zeros(
            6
        )

        self.last_update = self.get_clock().now()

        if not self.init():

            raise RuntimeError(
                'No thrusters/fins found'
            )

        self.sub = self.create_subscription(
            AUVCommand,
            'control_input',
            self.control_callback,
            10
        )

        self.timer = self.create_timer(
            1.0 / self.update_rate,
            self.update_loop
        )


    def init(self):

        self.delta = casadi.SX.sym(
            'delta',
            self.n_fins
        )

        actuator_model = (
            self.thruster.tam_column.reshape(
                (6, 1)
            )
            *
            self.thrust
        )

        for i in self.fins:

            f_lift = (

                0.5 *

                self.fin_config[
                    'fluid_density'
                ]

                *

                self.fin_config[
                    'lift_coefficient'
                ]

                *

                self.fin_config[
                    'fin_area'
                ]

                *

                self.delta[i]

                *

                self.u**2
            )

            f_lift = (

                f_lift

                *

                self.fins[i].lift_vector
            )

            t_lift = casadi.cross(
                self.fins[i].pos,
                f_lift
            )

            actuator_model += casadi.vertcat(
                f_lift,
                t_lift
            )

        self.cost_function = casadi.norm_2(

            self.output_tau

            -

            actuator_model

        )

        return True


    def update_loop(self):

        now = self.get_clock().now()

        if self.timeout > -1:

            dt = (
                now -
                self.last_update
            ).nanoseconds / 1e9

            if dt > self.timeout:

                self.input_surge_speed = 0.0

                self.input_tau = np.zeros(
                    6
                )

        output = self.allocate(

            self.input_tau,

            self.input_surge_speed

        )

        self.publish_commands(
            output
        )


    def allocate(
        self,
        tau,
        u
    ):

        output = np.zeros(
            self.n_fins + 1
        )

        if u == 0:

            return output

        if np.linalg.norm(
            tau
        ) == abs(
            tau[0]
        ):

            output[0] = (

                self.thruster.tam_column[0]

                *

                tau[0]

            )

        else:

            model = casadi.substitute(

                self.cost_function,

                casadi.vertcat(

                    self.output_tau,

                    self.u

                ),

                tau.tolist() + [u]

            )

            nlp = dict(

                x=casadi.vertcat(

                    self.thrust,

                    self.delta

                ),

                f=model

            )

            opts = {

                'verbose': False,

                'print_time': False,

                'ipopt.print_level': 0

            }

            solver = casadi.nlpsol(

                'solver',

                'ipopt',

                nlp,

                opts

            )

            sol = solver(

                lbx=[

                    -self.thruster_config[
                        'max_thrust'
                    ]

                ]

                +

                [

                    self.fin_lower_limit

                    for _ in range(
                        self.n_fins
                    )

                ],

                ubx=[

                    self.thruster_config[
                        'max_thrust'
                    ]

                ]

                +

                [

                    self.fin_upper_limit

                    for _ in range(
                        self.n_fins
                    )

                ]

            )

            for i in range(
                self.n_fins + 1
            ):

                output[i] = sol[
                    'x'
                ][i]

        return output


    def control_callback(
        self,
        msg
    ):

        self.input_surge_speed = (
            msg.surge_speed
        )

        self.input_tau = np.array([

            msg.command.force.x,

            msg.command.force.y,

            msg.command.force.z,

            msg.command.torque.x,

            msg.command.torque.y,

            msg.command.torque.z

        ])

        if 'ned' in msg.header.frame_id:

            self.input_tau[
                0:3
            ] = np.dot(

                self.base_link_ned_to_enu,

                self.input_tau[
                    0:3
                ]

            )

            self.input_tau[
                3:6
            ] = np.dot(

                self.base_link_ned_to_enu,

                self.input_tau[
                    3:6
                ]

            )

        self.last_update = (
            self.get_clock().now()
        )


def main():

    rclpy.init()

    node = AUVControlAllocator()

    rclpy.spin(
        node
    )

    node.destroy_node()

    rclpy.shutdown()


if __name__ == '__main__':

    main()
