
<?xml version="1.0"?>
<package format="2">

  <name>uuv_thruster_manager</name>
  <version>0.6.13</version>

  <description>
    ROS2 thruster manager package for UUV Simulator
  </description>

  <maintainer email="musa.marcusso@de.bosch.com">
    Musa Morena Marcusso Manhaes
  </maintainer>

  <license>Apache-2.0</license>

  <!-- Build tools -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>tf2_ros</exec_depend>

  <!-- Dependencies -->
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>uuv_gazebo_ros_plugins_msgs</depend>

  <!-- Interface runtime -->
  <exec_depend>rosidl_default_runtime</exec_depend>

  <!-- Python -->
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>python3-numpy</exec_depend>

  <!-- Tests -->
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>

