#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError
import cv2


class ImageResizer(Node):
    def __init__(self):
        super().__init__('image_resizer')

        self.bridge = CvBridge()
        self.image_sub = self.create_subscription(
            Image,
            '/blueview_p900/sonar_image',
            self.callback,
            10)
        self.resized_image_pub = self.create_publisher(
            Image,
            '/blueview_p900/sonar_image_resized',
            10)

    def callback(self, image_msg):
        try:
            cv_image = self.bridge.imgmsg_to_cv2(image_msg, desired_encoding='bgr8')
            height, width = cv_image.shape[:2]
            new_width = width 
            new_height = height // 2
            resized_image = cv2.resize(cv_image, (new_width, new_height))
            resized_image_msg = self.bridge.cv2_to_imgmsg(resized_image, encoding='bgr8')
            self.resized_image_pub.publish(resized_image_msg)
        except CvBridgeError as e:
            self.get_logger().error(f'CvBridge Error: {e}')


if __name__ == '__main__':
    rclpy.init()
    node = ImageResizer()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()
