<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>uuv_smac_utils</name>
  <version>0.6.13</version>
  <description>Utility scripts and configuration for the SMAC optimization</description>

  <maintainer email="musa.marcusso@de.bosch.com">Musa Morena Marcusso Manhaes</maintainer>

  <license>Apache-2.0</license>

  <author email="musa.marcusso@de.bosch.com">Musa Morena Marcusso Manhaes</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>uuv_simulation_evaluation</build_depend>

  <exec_depend>uuv_simulation_evaluation</exec_depend>
  <exec_depend>uuv_simulation_wrapper</exec_depend>
  <exec_depend>ros2cli</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>python3-matplotlib</exec_depend>
  <exec_depend>python3-simplejson</exec_depend>
  <exec_depend>python3-numpy</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
