<?xml version="1.0"?>
<package format="3">

  <name>uuv_batch_run_example</name>
  <version>0.5.0</version>

  <description>
    Batch simulation execution examples for ROS 2, Gazebo Harmonic and GZ Sim 8.
  </description>

  <maintainer email="musa.marcusso@de.bosch.com">
    Musa Morena Marcusso Manhaes
  </maintainer>

  <license>Apache-2.0</license>

  <!-- Build system -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- ROS 2 launch system -->
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <!-- Gazebo Harmonic / GZ Sim -->
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
