<?xml version="1.0"?>
<package format="3">
  <name>rexrov2_gazebo</name>
  <version>0.1.3</version>
  <description>Launch files for RexROV2 simulation demos in ROS2</description>

  <maintainer email="musa@example.com">RexROV Team</maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>rexrov2_description</exec_depend>
  <exec_depend>rexrov2_control</exec_depend>

</package>
