#!/usr/bin/env python3

import math

import rclpy
from geometry_msgs.msg import TransformStamped
from rclpy.node import Node
from tf2_ros import StaticTransformBroadcaster


class WorldNedFramePublisher(Node):
    def __init__(self):
        super().__init__("world_ned_frame_publisher")
        self.broadcaster = StaticTransformBroadcaster(self)

        transform = TransformStamped()
        transform.header.stamp = self.get_clock().now().to_msg()
        transform.header.frame_id = "world"
        transform.child_frame_id = "world_ned"
        transform.transform.translation.x = 0.0
        transform.transform.translation.y = 0.0
        transform.transform.translation.z = 0.0

        yaw = math.pi / 2.0
        roll = math.pi
        cy = math.cos(yaw * 0.5)
        sy = math.sin(yaw * 0.5)
        cr = math.cos(roll * 0.5)
        sr = math.sin(roll * 0.5)

        transform.transform.rotation.x = sr * cy
        transform.transform.rotation.y = sr * sy
        transform.transform.rotation.z = cr * sy
        transform.transform.rotation.w = cr * cy
        self.broadcaster.sendTransform(transform)


def main():
    rclpy.init()
    node = WorldNedFramePublisher()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()


if __name__ == "__main__":
    main()
