<?xml version="1.0"?>

<package format="3">

  <name>uuv_control_cascaded_pid</name>

  <version>0.6.13</version>

  <description>
    Cascade PID controllers for
    acceleration, velocity and
    position control
  </description>

  <maintainer email="musa.marcusso@de.bosch.com">
    Musa Morena Marcusso Manhaes
  </maintainer>

  <maintainer email="sebastian.scherer2@de.bosch.com">
    Sebastian Scherer
  </maintainer>

  <maintainer email="luizricardo.douat@de.bosch.com">
    Luiz Ricardo Douat
  </maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>
    ament_cmake
  </buildtool_depend>

  <buildtool_depend>
    ament_python
  </buildtool_depend>

  <depend>rclpy</depend>

  <depend>geometry_msgs</depend>

  <depend>nav_msgs</depend>

  <depend>tf_transformations</depend>

  <depend>std_msgs</depend>

  <exec_depend>
    python3-numpy
  </exec_depend>

  <exec_depend>
    python3
  </exec_depend>

  <export>
    <build_type>
      ament_cmake
    </build_type>
  </export>

</package>
