<?xml version="1.0"?>
<package format="3">
  <name>rexrov2_control</name>
  <version>0.1.3</version>

  <description>
    Launch and configuration package for RexROV2 controllers using uuv_trajectory_control.
  </description>

  <maintainer email="Musa.Marcusso@de.bosch.com">Musa Morena Marcusso Manhaes</maintainer>
  <maintainer email="sebastian.scherer2@de.bosch.com">Sebastian Scherer</maintainer>
  <maintainer email="LuizRicardo.Douat@de.bosch.com">Luiz Ricardo Douat</maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Runtime dependencies -->
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>gazebo_ros2_control</exec_depend>

  <exec_depend>uuv_control_cascaded_pid</exec_depend>
  <exec_depend>uuv_thruster_manager</exec_depend>
  <exec_depend>uuv_trajectory_control</exec_depend>

  <exec_depend>rviz2</exec_depend>

</package>
